package com.cdg.business.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.apache.commons.lang3.SerializationUtils;
import org.hibernate.annotations.Where;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Where(clause = "deleted = 0")
public class Client implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id @GeneratedValue
	private long id;

	@NotNull
	@Size
	private String nomcli;

	@NotNull
	@Size
	private String ville;


	public Client() {
		super();
	}

	public Client(long id) {
		this.id = id;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNomcli() {
		return nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getVille() {
		return ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}
	
	public Client(String nomcli, String ville) {
		super();
		this.nomcli = nomcli;
		this.ville = ville;
	}
	
	private boolean deleted = false;

	
	public boolean isDeleted() {
		return deleted;
	}


	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	
	@Override
	public String toString() {
		return "Client [nomcli=" + nomcli + ", ville=" + ville + "]";
	}
	
	public Client updateProperties(Client client){
		this.nomcli = client.nomcli;
		this.ville = client.ville;
		return this;
	}


	@Transient
    private transient Client savedState;

    @PostLoad
    private void saveState(){
       this.savedState = SerializationUtils.clone(this); // from apache commons-lang
    }
}
