package com.cdg.business.model;

import java.io.Serializable;
import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.apache.commons.lang3.SerializationUtils;
import org.hibernate.annotations.Where;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Where(clause = "deleted = 0")
@Table(name="commande")
public class Commande implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id @GeneratedValue
	private long id;
	
	@Temporal(TemporalType.DATE)
	@NotNull
	private Date datecom;

	@NotNull
	@Size
	private Long idcli;


	public Commande() {
		super();
	}

	public Commande(long id) {
		this.id = id;
	}

	public Date getDatecom() {
		return datecom;
	}

	public void setDatecom(Date datecom) {
		this.datecom = datecom;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getIdcli() {
		return idcli;
	}

	public void setIdcli(Long idcli) {
		this.idcli = idcli;
	}
	
	public Commande(Date datecom) {
		super();
		this.datecom = datecom;
	}
	
	private boolean deleted = false;

	
	public boolean isDeleted() {
		return deleted;
	}


	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	
	public Commande updateProperties(Commande commande){
		this.datecom = commande.datecom;
		return this;
	}


	@Transient
    private transient Commande savedState;

    @PostLoad
    private void saveState(){
       this.savedState = SerializationUtils.clone(this); // from apache commons-lang
    }
}
