package com.cdg.business.dto;
import com.cdg.business.model.Commande;

import java.util.Date;

import com.cdg.business.model.Client;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class ClientDTO {
	private long id;

	private String nomcli;

	private String ville;
	
	private boolean deleted = false;


	public ClientDTO() {
	}

	public ClientDTO(long id) {
		this.id = id;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNomcli() {
		return nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getVille() {
		return ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}
	
	public ClientDTO(String nomcli, String ville, boolean deleted) {
		super();
		this.nomcli = nomcli;
		this.ville = ville;
		this.deleted = deleted;
	}
	
	public boolean isDeleted() {
		return deleted;
	}
	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
}
