package com.cdg.business.dto;
import com.cdg.business.model.Commande;
import com.cdg.business.model.Client;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class CommandeDTO {
	private Date datecom;

	private long id;

	private Long idcli;
	private boolean deleted = false;


	public CommandeDTO() {
	}

	public CommandeDTO(long id) {
		this.id = id;
	}

	public Date getDatecom() {
		return datecom;
	}

	public void setDatecom(Date datecom) {
		this.datecom = datecom;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getIdcli() {
		return idcli;
	}

	public void setIdcli(Long idcli) {
		this.idcli = idcli;
	}
	
	public boolean isDeleted() {
		return deleted;
	}
	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	
	public CommandeDTO(Date datecom, boolean deleted) {
		super();
		this.datecom = datecom;
		this.deleted = deleted;
	}
	
}
